# Generated by Django 2.2.6 on 2020-01-05 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='view',
        ),
    ]
