# Generated by Django 2.2.6 on 2020-02-27 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='view',
        ),
    ]
