# Generated by Django 2.2.6 on 2020-03-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20200302_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visiblity',
            field=models.BooleanField(default=True),
        ),
    ]
