# Generated by Django 2.2.6 on 2020-03-04 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_post_visiblity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='visiblity',
            new_name='visibility',
        ),
    ]
