# Generated by Django 2.2.6 on 2020-04-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20200304_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='home_show',
            field=models.BooleanField(default=False),
        ),
    ]
