# Generated by Django 2.2.6 on 2020-04-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_category_home_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='...')),
                ('image', models.ImageField(upload_to='homeimage')),
            ],
        ),
    ]
