# Generated by Django 2.2.6 on 2020-06-21 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlike',
            name='post',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='post.Post'),
            preserve_default=False,
        ),
    ]
