# Generated by Django 2.2.6 on 2020-03-02 18:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_searh'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Searh',
            new_name='Search',
        ),
    ]
