# Generated by Django 2.2.6 on 2020-03-02 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200302_1819'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
